AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  DatabaseName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /athan/{DEPLOYMENT_ENVIRONMENT}/athan-tracker-database-name

Globals:
  Function:
    MemorySize: 128
    Timeout: 10
    Runtime: nodejs16.x
    Tracing: Active
    Environment:
      Variables:
        DB_TABLE_NAME: !Ref DatabaseName

Resources:
  TrackerApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowHeaders:
          - '*'
        AllowMethods:
          - '*'
        AllowOrigins:
          - http://*
          - https://*

  TrackData:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-TrackDataFunction
      CodeUri: dist
      Handler: index.trackDataHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DatabaseName
      Events:
        CreateDataEvent:
          Type: HttpApi
          Properties:
            Path: /track
            Method: POST
            ApiId: !Ref TrackerApi
            PayloadFormatVersion: '2.0'

Outputs:
  HttpApiURL:
    Description: 'TRACKER API URL'
    Value: !Sub 'https://${TrackerApi}.execute-api.${AWS::Region}.amazonaws.com/'
