AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    MemorySize: 128
    Timeout: 10
    Runtime: nodejs16.x
    Tracing: Active

Parameters:
  DatabaseName:
    Type: String
    Default: athan-tracker-db-dev

Resources:
  TrackerApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowHeaders:
          - '*'
        AllowMethods:
          - '*'
        AllowOrigins:
          - http://*
          - https://*

  CreateData:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-CreateDataFunction
      CodeUri: dist
      Handler: index.createDataHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DatabaseName
      Events:
        CreateDataEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
            ApiId: !Ref TrackerApi

Outputs:
  HttpApiURL:
    Description: 'TRACKER API URL'
    Value: !Sub 'https://${TrackerApi}.execute-api.${AWS::Region}.amazonaws.com/'
