AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  AlexaLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-lambda-handler
      CodeUri: dist
      Handler: index.handler
      MemorySize: 128
      Timeout: 10
      Runtime: nodejs14.x
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
          Properties:
            SkillId: amzn1.ask.skill.b2707d76-213a-4a54-9905-84fad81eb7be
