AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  AlexaLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-lambda-handler
      CodeUri: dist
      Handler: index.handler
      MemorySize: 128
      Timeout: 10
      Runtime: nodejs14.x
      Tracing: Active
