AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  AlexaSkillId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /athan/{DEPLOYMENT_ENVIRONMENT}/alexa-skill-id

Resources:
  AlexaLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-lambda-handler
      CodeUri: dist
      Handler: index.handler
      MemorySize: 128
      Timeout: 10
      Runtime: nodejs14.x
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
          Properties:
            SkillId: !Ref AlexaSkillId
