version = 0.1

[default.deploy.parameters]
debug                   = true
disable_rollback        = false
confirm_changeset       = false
fail_on_empty_changeset = false

[DEV.deploy.parameters]
region        = "us-east-2"
s3_bucket     = "athan-backend-dev"
s3_prefix     = "tracker-database-dev"
stack_name    = "athan-tracker-database-dev"
template_file = "template.dev.yaml"
capabilities  = "CAPABILITY_IAM"

[PROD.deploy.parameters]
region        = "us-east-2"
s3_bucket     = "athan-backend-prod"
s3_prefix     = "tracker-database-prod"
stack_name    = "athan-tracker-database-prod"
template_file = "template.prod.yaml"
capabilities  = "CAPABILITY_IAM"
