name: alexa-skill to PROD

on:
  push:
    branches:
      - main
    paths:
      - stacks/alexa-skill/**/*.ts
      - stacks/alexa-skill/**/*.json
      - stacks/alexa-skill/**/*.yaml
      - stacks/alexa-skill/**/*.toml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: deploy to PROD
        working-directory: stacks/alexa-skill
        run: |
          npm ci
          aws sts get-caller-identity
          npm run deploy
